# Generated by Django 5.2.5 on 2026-05-09 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviews_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'product')},
        ),
    ]
